/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Run {

    public static void main(String[] args) {
        Mobile mobile = new Mobile ("3310", "White", "Nokia");
        mobile.makeACall("UWOT bullet");
        Mobile iPhone = new IPhone("IPhone 10", "Black", "Apple");
        iPhone.makeACall("No more apple product please");
        Mobile android = new AndroidPhone( "G7 ThinQ", "Black", "LG");
        android.makeACall("Hail Android Forever");

        Person tom = new Person(mobile, "Tom");
        tom.personMakeACall("I am " + tom.getName());

        tom.setMobile(iPhone);
        tom.personMakeACall("I am " + tom.getName());

        tom.setMobile(android);
        tom.personMakeACall("I am " + tom.getName());

        IPhoneRobot robot = new IPhoneRobot("Robot", mobile);
        robot.robotMakeACall("Robot Message: ");
        robot.setMobile(iPhone);
        robot.robotMakeACall("Robot Message: ");
        robot.setMobile(android);
        robot.robotMakeACall("Robot Message: ");

    }
}
